'use client';

export const dynamic = 'force-dynamic';

import React, { useState} from 'react';
import { useStaff } from '@caterkingapp/shared/hooks/useStaff';
import { useToast } from '@caterkingapp/shared/hooks/useToast';
import { useUser } from '@caterkingapp/shared/hooks/useUser';
import { StaffAssignment } from '../../components/StaffAssignment';
import { OfflineBanner } from '../../components/offline-banner';

interface Staff {
  id: string;
  display_name: string;
  role: string;
  status: string;
  presence: 'online' | 'idle' | 'offline';
  shift_start?: string;
  shift_end?: string;
}

interface StaffFormData {
  display_name: string;
  role: string;
  shift_start: string;
  shift_end: string;
}

export default function StaffPage() {
  const {
    data: staff,
    isLoading,
    createStaff,
    updateStaff,
    deleteStaff,
    realtimeState,
  } = useStaff();
  const { addToast } = useToast();
  const { data: user } = useUser();
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingStaff, setEditingStaff] = useState<Staff | null>(null);
  const [formData, setFormData] = useState<StaffFormData>({
    display_name: '',
    role: 'staff',
    shift_start: '',
    shift_end: '',
  });

  const canManageStaff = user && ['owner', 'manager'].includes(user.role);

  const handleCreate = async () => {
    try {
      await createStaff({
        ...formData,
        id: '', // Will be generated by database
        company_id: '', // Will be set by hook
        status: 'active',
        role: formData.role as any, // Type assertion for role enum
      });
      addToast('Staff member added successfully', 'success');
      setIsFormOpen(false);
      resetForm();
    } catch (error) {
      addToast('Failed to add staff member', 'error');
    }
  };

  const handleUpdate = async () => {
    if (!editingStaff) return;
    try {
      await updateStaff({
        ...editingStaff,
        ...formData,
        role: formData.role as any, // Type assertion for role enum
      });
      addToast('Staff member updated successfully', 'success');
      setEditingStaff(null);
      resetForm();
    } catch (error) {
      addToast('Failed to update staff member', 'error');
    }
  };

  const handleDelete = async (staffId: string) => {
    if (!confirm('Are you sure you want to delete this staff member?')) return;
    try {
      await deleteStaff(staffId);
      addToast('Staff member deleted successfully', 'success');
    } catch (error) {
      addToast('Failed to delete staff member', 'error');
    }
  };

  const resetForm = () => {
    setFormData({
      display_name: '',
      role: 'staff',
      shift_start: '',
      shift_end: '',
    });
  };

  const openEditForm = (staffMember: Staff) => {
    setEditingStaff(staffMember);
    setFormData({
      display_name: staffMember.display_name,
      role: staffMember.role,
      shift_start: staffMember.shift_start || '',
      shift_end: staffMember.shift_end || '',
    });
  };

  if (isLoading) return <div className="p-4">Loading staff...</div>;

  return (
    <div className="p-6">
      {!realtimeState.isConnected && <OfflineBanner />}
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold">Staff Management</h1>
        {canManageStaff && (
          <button
            onClick={() => setIsFormOpen(true)}
            className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
          >
            Add Staff Member
          </button>
        )}
      </div>

      <StaffAssignment />

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {staff?.map((staffMember: any) => (
          <div key={staffMember.id} className="bg-white p-4 rounded-lg shadow">
            <div className="flex items-center justify-between mb-2">
              <h3 className="font-semibold text-lg">{staffMember.display_name}</h3>
              <div
                className={`w-3 h-3 rounded-full ${
                  staffMember.presence === 'online'
                    ? 'bg-green-500'
                    : staffMember.presence === 'idle'
                      ? 'bg-yellow-500'
                      : 'bg-red-500'
                }`}
                title={`Presence: ${staffMember.presence}`}
              />
            </div>
            <p className="text-gray-600">Role: {staffMember.role}</p>
            <p className="text-gray-600">Status: {staffMember.status}</p>
            {staffMember.shift_start && staffMember.shift_end && (
              <p className="text-sm text-gray-500">
                Shift: {staffMember.shift_start} - {staffMember.shift_end}
              </p>
            )}
            {canManageStaff && (
              <div className="mt-4 flex gap-2">
                <button
                  onClick={() => openEditForm(staffMember)}
                  className="px-3 py-1 bg-yellow-500 text-white rounded text-sm hover:bg-yellow-600"
                >
                  Edit
                </button>
                <button
                  onClick={() => handleDelete(staffMember.id)}
                  className="px-3 py-1 bg-red-500 text-white rounded text-sm hover:bg-red-600"
                >
                  Delete
                </button>
              </div>
            )}
          </div>
        ))}
      </div>

      {(isFormOpen || editingStaff) && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-lg p-6 w-full max-w-md">
            <h2 className="text-xl font-bold mb-4">
              {editingStaff ? 'Edit Staff Member' : 'Add Staff Member'}
            </h2>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium mb-1">Name</label>
                <input
                  type="text"
                  value={formData.display_name}
                  onChange={(e) =>
                    setFormData((prev) => ({ ...prev, display_name: e.target.value }))
                  }
                  className="w-full p-2 border rounded"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Role</label>
                <select
                  value={formData.role}
                  onChange={(e) => setFormData((prev) => ({ ...prev, role: e.target.value }))}
                  className="w-full p-2 border rounded"
                >
                  <option value="staff">Staff</option>
                  <option value="manager">Manager</option>
                  <option value="event_lead">Event Lead</option>
                  <option value="owner">Owner</option>
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Shift Start</label>
                <input
                  type="time"
                  value={formData.shift_start}
                  onChange={(e) =>
                    setFormData((prev) => ({ ...prev, shift_start: e.target.value }))
                  }
                  className="w-full p-2 border rounded"
                />
              </div>
              <div>
                <label className="block text-sm font-medium mb-1">Shift End</label>
                <input
                  type="time"
                  value={formData.shift_end}
                  onChange={(e) => setFormData((prev) => ({ ...prev, shift_end: e.target.value }))}
                  className="w-full p-2 border rounded"
                />
              </div>
              <div className="flex gap-2">
                <button
                  onClick={editingStaff ? handleUpdate : handleCreate}
                  className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
                >
                  {editingStaff ? 'Update' : 'Add'}
                </button>
                <button
                  onClick={() => {
                    setIsFormOpen(false);
                    setEditingStaff(null);
                    resetForm();
                  }}
                  className="px-4 py-2 bg-gray-500 text-white rounded hover:bg-gray-600"
                >
                  Cancel
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
